# Generated by Flutter
# To build an app, use `flutter build ios`.

require 'json'
require 'pathname'

def flutter_install_all_ios_pods(ios_application_path = nil)
  flutter_install_ios_plugin_pods(ios_application_path)
end

def flutter_install_ios_plugin_pods(ios_application_path = nil)
  ios_application_path ||= File.dirname(File.realpath(__FILE__))
  project_path = File.expand_path('..', ios_application_path)
  
  # The file is in the project root.
  plugins_file = File.join(project_path, '.flutter-plugins-dependencies')
  
  unless File.exist?(plugins_file)
    plugins_file = File.join(Dir.pwd, '.flutter-plugins-dependencies')
  end
  
  return unless File.exist?(plugins_file)
  
  config = JSON.parse(File.read(plugins_file))
  plugins = config['plugins']['ios'] || []
  
  plugins.each do |plugin|
    name = plugin['name']
    path = plugin['path']
    next if name.nil? || path.nil?
    
    # Check if 'ios' directory exists. If not, use the path directly (federated plugin)
    ios_path = File.join(path, 'ios')
    if File.exist?(ios_path)
      pod name, :path => ios_path
    else
      # For federated plugins (like audioplayers_darwin), podspec is often in the root
      pod name, :path => path
    end
  end
end

def flutter_additional_ios_build_settings(target)
  return unless target.platform_name == :ios
  
  target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
  end
end
