# Generated by Flutter
# To build an app, use `flutter build ios`.

require 'json'
require 'pathname'

def flutter_install_all_ios_pods(ios_application_path = nil)
  flutter_install_ios_plugin_pods(ios_application_path)
end

def flutter_install_ios_plugin_pods(ios_application_path = nil)
  ios_application_path ||= File.dirname(File.realpath(__FILE__))
  # If ios_application_path is 'ios', then project_path should be root.
  # So we don't need another '..'
  project_path = File.expand_path('..', ios_application_path)
  
  # The file is in the project root.
  plugins_file = File.join(project_path, '.flutter-plugins-dependencies')
  
  # Check if we were passed 'ios' or root or something else
  unless File.exist?(plugins_file)
    # Check current directory
    plugins_file = File.join(Dir.pwd, '.flutter-plugins-dependencies')
  end
  
  return unless File.exist?(plugins_file)
  
  config = JSON.parse(File.read(plugins_file))
  plugins = config['plugins']['ios'] || []
  
  plugins.each do |plugin|
    name = plugin['name']
    path = plugin['path']
    next if name.nil? || path.nil?
    
    # In Ruby, if path is from Windows, we need to ensure it's handled or ignore it
    # But as we confirmed, Codemagic generates it, so it should be a Mac path
    pod name, :path => File.join(path, 'ios')
  end
end

def flutter_additional_ios_build_settings(target)
  return unless target.platform_name == :ios
  
  target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
  end
end
