# Generated by Flutter
# To build an app, use `flutter build ios`.

require 'json'
require 'pathname'

# The path to the Flutter root.
def flutter_root
  flutter_root_path = ENV['FLUTTER_ROOT']
  if flutter_root_path.nil? || flutter_root_path.empty?
    # Set to a default if not found (for local testing).
    # But on Codemagic it will be set.
    return nil
  end
  flutter_root_path
end

def flutter_install_all_ios_pods(ios_application_path = nil)
  flutter_install_ios_plugin_pods(ios_application_path)
end

def flutter_install_ios_plugin_pods(ios_application_path = nil)
  ios_application_path ||= File.dirname(File.realpath(__FILE__))
  project_path = File.expand_path('..', ios_application_path)
  
  # This file is generated by `flutter pub get`.
  plugins_file = File.join(project_path, '..', '.flutter-plugins-dependencies')
  return unless File.exist?(plugins_file)
  
  config = JSON.parse(File.read(plugins_file))
  plugins = config['plugins']['ios'] || []
  
  plugins.each do |plugin|
    name = plugin['name']
    path = plugin['path']
    pod name, :path => File.join(path, 'ios')
  end
end

def flutter_additional_ios_build_settings(target)
  return unless target.platform_name == :ios
  
  target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
  end
end
